// THIS FILE WILL BE OVERWRITTEN BY DEV-C++!
// DO NOT EDIT!

#ifndef DCEMU_PRIVATE_H
#define DCEMU_PRIVATE_H

// VERSION DEFINITIONS
#define VER_STRING	"0.0.1.446"
#define VER_MAJOR	0
#define VER_MINOR	0
#define VER_RELEASE	1
#define VER_BUILD	446
#define COMPANY_NAME	""
#define FILE_VERSION	""
#define FILE_DESCRIPTION	"DCEMU - Dreamcast Emulator"
#define INTERNAL_NAME	"DCEMU"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"DCEMU.EXE"
#define PRODUCT_NAME	"DCEMU"
#define PRODUCT_VERSION	""

#endif //DCEMU_PRIVATE_H
