CPP  = g++
CC   = gcc

OBJ  = ./obj/graficos.o ./obj/main.o ./obj/mem.o ./obj/mmu.o ./obj/excepciones.o ./obj/log.o ./obj/BFont.o ./obj/reg.o ./obj/intc.o ./obj/arith.o ./obj/branch.o ./obj/dcopcodes.o ./obj/gdrom.o ./obj/opciones.o ./obj/sistema.o ./obj/traza.o ./obj/wdt.o ./obj/tmu.o ./obj/floatcontrol.o ./obj/floatgraph.o ./obj/floatsimple.o ./obj/logic.o ./obj/mov.o ./obj/shift.o ./obj/syscontrol.o ./obj/opcodes.o ./obj/sh4emu.o ./obj/debug.o ./obj/iso.o ./obj/iso9660_min.o ./obj/cdi.o ./obj/mando.o ./obj/ta.o ./obj/ubc.o ./obj/vram.o ./obj/g2dma.o ./obj/aica.o ./obj/arm7.o ./obj/audio.o ./obj/scramble.o ./obj/gui.o ./obj/glops.o
LINKOBJ  = ./obj/graficos.o ./obj/main.o ./obj/mem.o ./obj/mmu.o ./obj/excepciones.o ./obj/log.o ./obj/BFont.o ./obj/reg.o ./obj/intc.o ./obj/arith.o ./obj/branch.o ./obj/dcopcodes.o ./obj/gdrom.o ./obj/opciones.o ./obj/sistema.o ./obj/traza.o ./obj/wdt.o ./obj/tmu.o ./obj/floatcontrol.o ./obj/floatgraph.o ./obj/floatsimple.o ./obj/logic.o ./obj/mov.o ./obj/shift.o ./obj/syscontrol.o ./obj/opcodes.o ./obj/sh4emu.o ./obj/debug.o ./obj/iso.o ./obj/iso9660_min.o ./obj/cdi.o ./obj/mando.o ./obj/ta.o ./obj/ubc.o ./obj/vram.o ./obj/g2dma.o ./obj/scramble.o ./obj/gui.o ./obj/glops.o


LIBS = `sdl-config --libs` -Llib/linux -lSDLmain -lSDL -lcdio -lGL -liso9660 -lguichan_opengl -lguichan_sdl -lguichan -lSIMDx86

INCS = `sdl-config --cflags`
CXXINCS = `sdl-config --cflags`  

BIN  = dcemu
CXXFLAGS = $(CXXINCS) -O2 -DPOSX  -DUSE_GUICHAN
CFLAGS = $(INCS) -Wall -Iinclude  -O3  -DPOSX -DX86_OPT -fno-strict-aliasing -DUSE_LIBCDIO

.PHONY: all all-before all-after clean clean-custom

all: all-before dcemu all-after


clean: clean-custom
	rm -f $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "dcemu" $(LIBS)

./obj/graficos.o: graficos.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h   graficos.h intc.h gui.h render.h vram.h
	$(CC) -c graficos.c -o ./obj/graficos.o $(CFLAGS)

./obj/main.o: main.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h BFont.h branch.h intc.h debug.h graficos.h iso.h gui.h gdrom.h opciones.h sistema.h traza.h
	$(CC) -c main.c -o ./obj/main.o $(CFLAGS)

./obj/mem.o: mem.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h intc.h   graficos.h gui.h gdrom.h opciones.h sistema.h traza.h mmu.h vram.h g2dma.h aica.h
	$(CC) -c mem.c -o ./obj/mem.o $(CFLAGS)

./obj/mmu.o: mmu.c mmu.h lnxdefs.h log.h excepciones.h sh4emu.h
	$(CC) -c mmu.c -o ./obj/mmu.o $(CFLAGS)

./obj/excepciones.o: excepciones.c excepciones.h lnxdefs.h log.h mmu.h sh4emu.h
	$(CC) -c excepciones.c -o ./obj/excepciones.o $(CFLAGS)

./obj/log.o: log.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h gui.h
	$(CC) -c log.c -o ./obj/log.o $(CFLAGS)

./obj/BFont.o: BFont.c BFont.h
	$(CC) -c BFont.c -o ./obj/BFont.o $(CFLAGS)

./obj/reg.o: reg.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h
	$(CC) -c reg.c -o ./obj/reg.o $(CFLAGS)

./obj/intc.o: intc.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h intc.h
	$(CC) -c intc.c -o ./obj/intc.o $(CFLAGS)

./obj/arith.o: arith.c sh4emu.h log.h mem.h options.h opcodes.h
	$(CC) -c arith.c -o ./obj/arith.o $(CFLAGS)

./obj/branch.o: branch.c sh4emu.h log.h mem.h options.h opcodes.h
	$(CC) -c branch.c -o ./obj/branch.o $(CFLAGS)

./obj/dcopcodes.o: dcopcodes.c main.h options.h reg.h log.h sh4emu.h mem.h   opcodes.h iso.h gdrom.h
	$(CC) -c dcopcodes.c -o ./obj/dcopcodes.o $(CFLAGS)

./obj/gdrom.o: gdrom.c gdrom.h main.h options.h reg.h log.h sh4emu.h mem.h   intc.h iso.h opciones.h traza.h
	$(CC) -c gdrom.c -o ./obj/gdrom.o $(CFLAGS)

./obj/opciones.o: opciones.c opciones.h options.h
	$(CC) -c opciones.c -o ./obj/opciones.o $(CFLAGS)

./obj/sistema.o: sistema.c sistema.h lnxdefs.h
	$(CC) -c sistema.c -o ./obj/sistema.o $(CFLAGS)

./obj/wdt.o: wdt.c wdt.h lnxdefs.h log.h
	$(CC) -c wdt.c -o ./obj/wdt.o $(CFLAGS)

./obj/tmu.o: tmu.c tmu.h lnxdefs.h log.h sh4emu.h
	$(CC) -c tmu.c -o ./obj/tmu.o $(CFLAGS)

./obj/traza.o: traza.c traza.h lnxdefs.h main.h options.h reg.h log.h sh4emu.h mem.h   opcodes.h debug.h
	$(CC) -c traza.c -o ./obj/traza.o $(CFLAGS)

./obj/floatcontrol.o: floatcontrol.c sh4emu.h log.h mem.h options.h opcodes.h
	$(CC) -c floatcontrol.c -o ./obj/floatcontrol.o $(CFLAGS)

./obj/floatgraph.o: floatgraph.c main.h options.h reg.h log.h sh4emu.h mem.h   opcodes.h
	$(CC) -c floatgraph.c -o ./obj/floatgraph.o $(CFLAGS)

./obj/floatsimple.o: floatsimple.c main.h options.h reg.h log.h sh4emu.h mem.h   opcodes.h floatsimple.h floatgraph.h
	$(CC) -c floatsimple.c -o ./obj/floatsimple.o $(CFLAGS)

./obj/logic.o: logic.c sh4emu.h log.h mem.h options.h opcodes.h
	$(CC) -c logic.c -o ./obj/logic.o $(CFLAGS)

./obj/mov.o: mov.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h
	$(CC) -c mov.c -o ./obj/mov.o $(CFLAGS)

./obj/shift.o: shift.c sh4emu.h log.h mem.h options.h opcodes.h
	$(CC) -c shift.c -o ./obj/shift.o $(CFLAGS)

./obj/syscontrol.o: syscontrol.c sh4emu.h log.h mem.h options.h opcodes.h
	$(CC) -c syscontrol.c -o ./obj/syscontrol.o $(CFLAGS)

./obj/opcodes.o: opcodes.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h   mov.h branch.h logic.h arith.h shift.h syscontrol.h floatsimple.h   floatcontrol.h dcopcodes.h floatgraph.h
	$(CC) -c opcodes.c -o ./obj/opcodes.o $(CFLAGS)

./obj/sh4emu.o: sh4emu.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h branch.h   floatsimple.h
	$(CC) -c sh4emu.c -o ./obj/sh4emu.o $(CFLAGS)

./obj/debug.o: debug.c main.h options.h reg.h log.h sh4emu.h mem.h opcodes.h   debug.h graficos.h BFont.h
	$(CC) -c debug.c -o ./obj/debug.o $(CFLAGS)

./obj/iso.o: iso.c iso.h iso9660_min.h include/cdio/cdio_config.h include/cdio/cdio.h   include/cdio/version.h include/cdio/types.h include/cdio/cdio_config.h   include/cdio/sector.h include/cdio/device.h include/cdio/disc.h   include/cdio/read.h include/cdio/cdtext.h include/cdio/track.h   include/cdio/iso9660.h include/cdio/ds.h include/cdio/xa.h   include/cdio/rock.h include/cdio/cd_types.h iso.h iso9660_min.h lnxdefs.h
	$(CC) -c iso.c -o ./obj/iso.o $(CFLAGS)

./obj/iso9660_min.o: iso9660_min.c iso9660_min.h
	$(CC) -c iso9660_min.c -o ./obj/iso9660_min.o $(CFLAGS)

./obj/cdi.o: cdi.c cdi.h
	$(CC) -c cdi.c -o ./obj/cdi.o $(CFLAGS)

./obj/mando.o: mando.c mando.h
	$(CC) -c mando.c -o ./obj/mando.o $(CFLAGS)

./obj/ta.o: ta.c ta.h graficos.h main.h lnxdefs.h
	$(CC) -c ta.c -o ./obj/ta.o $(CFLAGS)

./obj/ubc.o: ubc.c ubc.h excepciones.h sh4emu.h main.h lnxdefs.h
	$(CC) -c ubc.c -o ./obj/ubc.o $(CFLAGS)

./obj/vram.o: vram.c vram.h lnxdefs.h
	$(CC) -c vram.c -o ./obj/vram.o $(CFLAGS)

./obj/g2dma.o: g2dma.c g2dma.h main.h mem.h intc.h traza.h lnxdefs.h
	$(CC) -c g2dma.c -o ./obj/g2dma.o $(CFLAGS)

./obj/aica.o: aica.c aica.h main.h tmu.h intc.h traza.h arm7.h lnxdefs.h
	$(CC) -c aica.c -o ./obj/aica.o $(CFLAGS)

./obj/arm7.o: arm7.c arm7.h aica.h main.h lnxdefs.h
	$(CC) -c arm7.c -o ./obj/arm7.o $(CFLAGS)

./obj/audio.o: audio.c audio.h aica.h main.h opciones.h traza.h
	$(CC) -c audio.c -o ./obj/audio.o $(CFLAGS)

./obj/scramble.o: scramble.c
	$(CC) -c scramble.c -o ./obj/scramble.o $(CFLAGS)

./obj/glops.o: glops.c
	$(CC) -c glops.c -o ./obj/glops.o $(CFLAGS)

./obj/gui.o: gui.cpp gui.h
	$(CPP) -c gui.cpp -o ./obj/gui.o $(CXXFLAGS)
