# Project: dcemu
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = ./obj/dcemu_private.res
OBJ  = ./obj/graficos.o ./obj/main.o ./obj/mem.o ./obj/mmu.o ./obj/log.o ./obj/BFont.o ./obj/reg.o ./obj/intc.o ./obj/arith.o ./obj/branch.o ./obj/dcopcodes.o ./obj/gdrom.o ./obj/opciones.o ./obj/sistema.o ./obj/traza.o ./obj/wdt.o ./obj/tmu.o ./obj/floatcontrol.o ./obj/floatgraph.o ./obj/floatsimple.o ./obj/logic.o ./obj/mov.o ./obj/shift.o ./obj/syscontrol.o ./obj/opcodes.o ./obj/debug.o ./obj/iso.o ./obj/iso9660_min.o ./obj/scramble.o ./obj/gui.o ./obj/glops.o ./obj/sh4emu.o $(RES)
LINKOBJ  = ./obj/graficos.o ./obj/main.o ./obj/mem.o ./obj/mmu.o ./obj/log.o ./obj/BFont.o ./obj/reg.o ./obj/intc.o ./obj/arith.o ./obj/branch.o ./obj/dcopcodes.o ./obj/gdrom.o ./obj/opciones.o ./obj/sistema.o ./obj/traza.o ./obj/wdt.o ./obj/tmu.o ./obj/floatcontrol.o ./obj/floatgraph.o ./obj/floatsimple.o ./obj/logic.o ./obj/mov.o ./obj/shift.o ./obj/syscontrol.o ./obj/opcodes.o ./obj/debug.o ./obj/iso.o ./obj/iso9660_min.o ./obj/scramble.o ./obj/gui.o ./obj/glops.o ./obj/sh4emu.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows -Llib/win32 -lstdc++ -lmingw32 -lopengl32 -lglu32 -lSDLmain -lSDL -liso9660 -lcdio -lguichan_opengl -lguichan_sdl -lguichan -lSIMDx86 -lwinmm -mwindows  -march=athlon-xp -m3dnow 
INCS =  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/SDL" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/SDL" 
BIN  = dcemu.exe
CXXFLAGS = $(CXXINCS) -Wall   -fexceptions -fexpensive-optimizations -O3 -march=athlon-xp -m3dnow -DUSE_GUICHAN
CFLAGS = $(INCS) -Wall -Iinclude -DX86_OPT -DPOSX -fomit-frame-pointer -fno-strict-aliasing   -fexceptions -fexpensive-optimizations -O3 -march=athlon-xp -m3dnow -DUSE_LIBCDIO
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before dcemu.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "dcemu.exe" $(LIBS)

./obj/graficos.o: graficos.c
	$(CC) -c graficos.c -o ./obj/graficos.o $(CFLAGS)

./obj/main.o: main.c
	$(CC) -c main.c -o ./obj/main.o $(CFLAGS)

./obj/mem.o: mem.c
	$(CC) -c mem.c -o ./obj/mem.o $(CFLAGS)

./obj/mmu.o: mmu.c
	$(CC) -c mmu.c -o ./obj/mmu.o $(CFLAGS)

./obj/log.o: log.c
	$(CC) -c log.c -o ./obj/log.o $(CFLAGS)

./obj/BFont.o: BFont.c
	$(CC) -c BFont.c -o ./obj/BFont.o $(CFLAGS)

./obj/reg.o: reg.c
	$(CC) -c reg.c -o ./obj/reg.o $(CFLAGS)

./obj/intc.o: intc.c
	$(CC) -c intc.c -o ./obj/intc.o $(CFLAGS)

./obj/arith.o: arith.c
	$(CC) -c arith.c -o ./obj/arith.o $(CFLAGS)

./obj/branch.o: branch.c
	$(CC) -c branch.c -o ./obj/branch.o $(CFLAGS)

./obj/dcopcodes.o: dcopcodes.c
	$(CC) -c dcopcodes.c -o ./obj/dcopcodes.o $(CFLAGS)

./obj/gdrom.o: gdrom.c
	$(CC) -c gdrom.c -o ./obj/gdrom.o $(CFLAGS)

./obj/opciones.o: opciones.c
	$(CC) -c opciones.c -o ./obj/opciones.o $(CFLAGS)

./obj/sistema.o: sistema.c
	$(CC) -c sistema.c -o ./obj/sistema.o $(CFLAGS)

./obj/wdt.o: wdt.c
	$(CC) -c wdt.c -o ./obj/wdt.o $(CFLAGS)

./obj/tmu.o: tmu.c
	$(CC) -c tmu.c -o ./obj/tmu.o $(CFLAGS)

./obj/traza.o: traza.c
	$(CC) -c traza.c -o ./obj/traza.o $(CFLAGS)

./obj/floatcontrol.o: floatcontrol.c
	$(CC) -c floatcontrol.c -o ./obj/floatcontrol.o $(CFLAGS)

./obj/floatgraph.o: floatgraph.c
	$(CC) -c floatgraph.c -o ./obj/floatgraph.o $(CFLAGS)

./obj/floatsimple.o: floatsimple.c
	$(CC) -c floatsimple.c -o ./obj/floatsimple.o $(CFLAGS)

./obj/logic.o: logic.c
	$(CC) -c logic.c -o ./obj/logic.o $(CFLAGS)

./obj/mov.o: mov.c
	$(CC) -c mov.c -o ./obj/mov.o $(CFLAGS)

./obj/shift.o: shift.c
	$(CC) -c shift.c -o ./obj/shift.o $(CFLAGS)

./obj/syscontrol.o: syscontrol.c
	$(CC) -c syscontrol.c -o ./obj/syscontrol.o $(CFLAGS)

./obj/opcodes.o: opcodes.c
	$(CC) -c opcodes.c -o ./obj/opcodes.o $(CFLAGS)

./obj/debug.o: debug.c
	$(CC) -c debug.c -o ./obj/debug.o $(CFLAGS)

./obj/iso.o: iso.c
	$(CC) -c iso.c -o ./obj/iso.o $(CFLAGS)

./obj/iso9660_min.o: iso9660_min.c
	$(CC) -c iso9660_min.c -o ./obj/iso9660_min.o $(CFLAGS)

./obj/scramble.o: scramble.c
	$(CC) -c scramble.c -o ./obj/scramble.o $(CFLAGS)

./obj/gui.o: gui.cpp
	$(CPP) -c gui.cpp -o ./obj/gui.o $(CXXFLAGS)

./obj/glops.o: glops.c
	$(CC) -c glops.c -o ./obj/glops.o $(CFLAGS)

./obj/sh4emu.o: sh4emu.c
	$(CC) -c sh4emu.c -o ./obj/sh4emu.o $(CFLAGS)

./obj/dcemu_private.res: dcemu_private.rc 
	$(WINDRES) -i dcemu_private.rc --input-format=rc -o ./obj/dcemu_private.res -O coff 
